import { Router } from "express";
import multer from "multer";
import { put } from "@vercel/blob";
import { authenticate } from "../middleware/auth.middleware.js";

// ✅ FIX 1: Change memory orchestration to Buffer mode so Vercel's disk is never touched
const storage = multer.memoryStorage();

const upload = multer({
  storage,
  limits: { fileSize: 10 * 1024 * 1024 },
  fileFilter: (_req, file, cb) => {
    const allowed = ["image/", "video/", "application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"];
    if (allowed.some((t) => file.mimetype.startsWith(t) || file.mimetype === t)) {
      cb(null, true);
    } else {
      cb(new Error("Only image, video, PDF, and DOC files are allowed"));
    }
  },
});

const router = Router();

// ✅ FIX 2: Add `async` to the route callback to support streaming your upload out to the cloud
router.post("/", authenticate, upload.single("file"), async (req, res) => {
  try {
    if (!req.file) {
      res.status(400).json({ success: false, error: "No file uploaded" });
      return;
    }

    // Generate a secure, unique filename footprint for storage isolation
    const uniqueName = `${Date.now()}-${Math.round(Math.random() * 1e9)}-${req.file.originalname}`;

    // ✅ FIX 3: Stream file directly from RAM buffer into Vercel's cloud asset platform
    const blob = await put(uniqueName, req.file.buffer, {
      access: 'public',
      contentType: req.file.mimetype
    });

    const mediaType = req.file.mimetype.startsWith("video/") ? "VIDEO" : "IMAGE";

    // ✅ FIX 4: Return the permanent public CDN address (`blob.url`) generated by the cloud engine
    res.json({ 
      success: true, 
      data: { 
        url: blob.url, 
        mediaType 
      } 
    });
  } catch (error: any) {
    res.status(500).json({ success: false, error: error.message || "Cloud file streaming failure" });
  }
});

export default router;
